#!/bin/sh
# Run a command inside a nono sandbox with project-specific capabilities.
#
# DO NOT EDIT — regenerated by 'appbase update'.
# Customize project-specific flags in ./sandbox.flags instead.
#
# See: https://github.com/always-further/nono
set -e

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Graceful degradation: run unsandboxed if nono isn't installed
if ! command -v nono >/dev/null 2>&1; then
    echo "nono not found — running unsandboxed"
    exec "$@"
fi

# --- Pre-sandbox environment setup ---
# Tools that resolve paths at startup need help before entering the sandbox.

# Go: resolve GOROOT before sandbox (Go's trimmed binary can't follow symlinks under sandbox)
if command -v go >/dev/null 2>&1 && [ -z "$GOROOT" ]; then
    export GOROOT="$(go env GOROOT)"
fi

# PATH: ensure toolchain directories are on PATH (nono doesn't source shell profiles)
for p in /opt/homebrew/bin /usr/local/bin /usr/local/go/bin "$HOME/go/bin"; do
    case ":$PATH:" in
        *":$p:"*) ;;
        *) [ -d "$p" ] && export PATH="$p:$PATH" ;;
    esac
done

# Go binary: resolve its directory for the sandbox allowlist
GO_BIN_DIR=""
if command -v go >/dev/null 2>&1; then
    GO_BIN_DIR="$(dirname "$(command -v go)")"
fi

# Docker: nono blocks ~/.docker (contains registry credentials) — correct behavior.
# Create a local empty config to suppress Docker CLI warnings.
DOCKER_DIR="$PROJECT_DIR/.docker"
mkdir -p "$DOCKER_DIR" 2>/dev/null
[ -f "$DOCKER_DIR/config.json" ] || echo '{}' > "$DOCKER_DIR/config.json"
export DOCKER_CONFIG="$DOCKER_DIR"

# --- Interactive detection ---
EXEC_FLAG=""
case "$1" in
    claude|bash|zsh|sh|vim|nvim)
        EXEC_FLAG="--exec"  # Preserve TTY for interactive apps
        ;;
esac

# --- Build sandbox flags ---
GO_FLAG=""
if [ -n "$GO_BIN_DIR" ] && [ "$GO_BIN_DIR" != "/usr/bin" ]; then
    GO_FLAG="--read $GO_BIN_DIR"
fi

# --- Project-specific capabilities ---
# Sourced from ./sandbox.flags so this script can be regenerated freely.
#   --allow <path>         Read-write access
#   --read <path>          Read-only access
#   --allow-bind <port>    Allow binding to a port

APP_FLAGS=""
if [ -f "$PROJECT_DIR/sandbox.flags" ]; then
    . "$PROJECT_DIR/sandbox.flags"
fi

# --- Launch sandbox ---
exec nono run \
    --profile claude-code \
    --allow "$PROJECT_DIR" \
    $GO_FLAG \
    $APP_FLAGS \
    $EXEC_FLAG \
    -- "$@"
