SYNC_NUDGE_KEY: ENC[AES256_GCM,data:tWX+8AGVXQSjFChAQw1wf0JA4JVUEV8nAlfomI3+BRVLt7B2098URwKBGBfu46EaKDttXrQo1mdfapAEuIF9Pw==,iv:GDPomjV/175LS4gpGvgKv1788Xm+oHJWR2zZqxsDH6A=,tag:8pLW94ZxN8zwj+JNVylyeA==,type:str]
sops:
    age:
        - recipient: age1zs29ur6462tsgwjmqj58tld7qt78l8wlwx8w4h78qar5gqsjjygs8xthca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiai9LRjhmaGg0MkRYMTBC
            MGNCdkJ6VDJYZVFrSmtIdnlvYmYxb0lRY1E0Cm5qSDkzd2FFRGZQR0tIRmwvZXRn
            Ui96UjdqVUxSWUEzYVNPVWtuRGhpWWcKLS0tIEhrUithQU00VVVOUnNBWmVmODho
            NjYyckR2MFJGTmVSOVY2K0g3OXkrZU0KuZFDQOZStJhGz78VC2bynDsl2ljo28yu
            C2tHVOfy938Ivhe00Y1swDGxqUHf87kQo+QN21qifhf8XShTMMifdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T03:53:42Z"
    mac: ENC[AES256_GCM,data:fAxoyBM589UafzUb4jcle71RKTIDSlOZ+Ffe5ElGUQRruguP4zc6eajd6nu+eh7ZtUlIgLX81kMM6hjps+wrgMGma0klQcvk7nwhWu2XYd7So66vNRjDTc4e/3vewtm4KyO7PzcAY1EOCydqPX2SDHwnZv4xywV/cen2tbF+BZk=,iv:tE4+xLG+/gigHj334royCuOqvEE4+WBw7kDiwRTeQAY=,tag:Kqmxohw4O4q94uacPQ6J5A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
